name: Build and Push to ACR

on:
  push:
    branches: 
      - 'main' 
 
jobs: 
  build-and-push: 
    name: 'Build and Push Docker Image' 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
            --build-arg GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/my-image-name:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-image-name:latest
