name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: |
        docker build \
          --build-arg BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
          --build-arg GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
          . --file Dockerfile --tag my-image-name:$(date +%s)
