name: Build and Push to ACR

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: 'Build Docker Image'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set Image Tag
        id: set-tag
        run: echo "IMAGE_TAG=${{ secrets.ACR_LOGIN_SERVER }}/my-image-name:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
            --build-arg GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
            -t $IMAGE_TAG .  # Use the IMAGE_TAG from the environment variable

  push:
    name: 'Push Docker Image'
    runs-on: ubuntu-latest
    needs: build  # Ensure this job runs after the build job

    steps:
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push Docker Image
        run: |
          echo "Pushing image: $IMAGE_TAG"  # Log the image tag for debugging
          docker push $IMAGE_TAG  # Use the IMAGE_TAG from the environment variable
